---
- name: Backup Network Device Configurations
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Get Configuration and Save Locally
      ios_config:
        backup: yes
        backup_options:
          dir_path: "./backup/{{ inventory_hostname }}/"