---
- name: Backup Configurations
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: backup configuration
      ios_config:
        backup: yes
        backup_options:
          dir_path: "./backup/{{ inventory_hostname }}"
#      register: backup_location