---
- name:  Remove old local administrative accounts on IOS and IOS XE Devices
  hosts: IOS, IOSXE
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Remove a Local Account
      ios_user:
        name: "{{ item }}"
        state: absent
      loop: "{{ oldUsers }}"

    - name: Save Config on IOS and IOS XE Devices
      ios_config:
        save_when: always

- name:  Remove old local administrative accounts on NXOS Devices
  hosts: NXOS
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Remove a Local Account
      nxos_user:
        name: "{{ item }}"
        state: absent
      loop: "{{ oldUsers }}"

    - name: Save Config on NXOS Devices
      nxos_config:
        save_when: always