#Credit to @cdschr1 for the play and Tower support!

---
- name: Configure /etc/resolv.conf
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Remove immutable attibute from resolv.conf
      command: chattr -i /etc/resolv.conf

    - name: Edit/replace contents of /etc/resolv.conf
      copy:
        content: |
           domain local.ad
           nameserver {{ dns_server1 }}
           nameserver {{ dns_server2 }}
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0444
        attributes: +i
