---
- name: Trunk Port Configuration
  ios_l2_interfaces:
      config:
        - name: "{{ item.portNumber }}"
          trunk:
            - native_vlan: "{{ nativeVLAN }}"
              allowed_vlans: "{{ item.allowedVLANList }}"
  loop: "{{ trunk_ports }}"
